sudo: false

env:

language: php

services:
  - mysql

php:
  - 5.6
  - 7.0
  - nightly

before_install:

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - phpenv config-add php.ini.dist
  - mysql -e "create database IF NOT EXISTS gentelella;" -u root

script:
  - ./vendor/bin/php-cs-fixer fix --verbose --level=symfony
  - ./vendor/bin/phpunit

after_success:
after_failure:
after_script:
before_deploy:
deploy:
after_deploy:


